# Exceptions
Исключения используются, когда выполнение программы зашло в тупик. Это происходит, когда невозможно продолжать выполнение
приложения в нормальном режиме.

##### Применимость
Одно из важных применений исключений - возможность с помощью одной команды убрать всё со стека. Перехват исключений 
используется, чтобы позволять очистку стека до определенного момента. Представим, что снизу представлен стек с уровнями
вложенности:

1 -\
2 --\
3 --- catch (MyException e) { ... }\
4 ----\
5 ----- throw new MyException();\

В данном примере, выбрасывая исключение на 5-ом "листе" стека, можно вернуться сразу на третий, минуя остальные и
продолжить выполнение программы.

##### Выброшенное дважды не поймать
Exception, выброшенные из блока catch, не перехватываются дальше, даже если соответствуют сигнатуре.
```java
public class Start {
    public static void main(String[] args) {
        try {
            throw new NullPointerException();
        } catch (NullPointerException e) {
            throw e;
        } catch (Exception e) { // Здесь NPE не перехватится, хотя является наследником Exception
            System.out.println(e.getMessage());
        }
    }
}
```

##### System.err
`System.out` - буфферизованный поток вывода в консоль, а `System.err` - нет. Поэтому, в таком примере:
```java
public class Start {
    public static void main(String[] args) {
        System.out.println("Message");
        throw new Error("Error");
    }
}
```
может сначала вывестись `Message`, а затем `Error`, а может наоборот. Если же `System.out` заменить на `System.err`, то
всегда будет выведено сначала `Message`, потом `Error`.

##### Throw null
Java позволяет выбросить null-исключение: `throw null`. В этом случае происходит проверка аргумента и, в данном случае,
геренируется NullPointerException.